apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - name: postgres-cont
        image: postgres:latest
        imagePullPolicy: Always
        volumeMounts:
          - name:  postgres-data
            mountPath: /mnt/data/
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 5432
          name: postgres-port
