apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-depl
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-pod
        image: django_kubes-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
          protocol: TCP
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
