apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  labels:
    app: django-app
type: Opaque
data:
  secret_key: YUlxZmFrR0U3Uk0zR1d2cjdnRFlRd2VsT2RQV3JnUDcxQUtSMTlPcmxSNlUxWFNtWkp4aUd0ZzdJTWJWT2l0VA==
