apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  labels:
    app: django-app
spec:
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
