networks:
  kubes_network:
    driver: bridge

volumes:
  PostgresData:
  NginxLogs:

secrets:
  postgres_password:
    file: ./docker/secrets/postgres-password.txt
  django_secret_key:
    file: ./docker/secrets/django-secret-key.txt
  pg_admin_password:
    file: ./docker/secrets/pgadmin-password.txt

services:
  main_site:
    build: ./mykube
    container_name: app_django_kubes
    secrets:
      - django_secret_key
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main_site.rule=(Host(`johnpm.fr`) || Host(`176.31.162.80`))"
    env_file:
      - ./docker/environment/django.env
    environment:
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
    ports:
      - 8000:8000
    networks:
      - kubes_network

  quart:
    build: ./quart_api
    container_name: app_api_quart
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quart.rule=Host(`johnpm.fr`) && PathPrefix(`/quart`)"
    env_file:
      - ./docker/environment/quart.env
    ports:
      - 5000:5000
    networks:
      - kubes_network

  reverse-proxy:
    image: traefik:v3.1
    # command: --configFile=/docker/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/var/letsencrypt:/letsencrypt
      - ~/var/access.log:/var/log/access.log
      - ~/var/traefik.log:/var/log/traefik.log
      - ./docker/traefik:/etc/traefik
    networks:
      - kubes_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: app_pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`traefik.johnpm.fr`) && PathPrefix(`/pgadmin`)"
    ports:
      - 5050:80
    secrets:
      - pg_admin_password
    environment:
      - PGADMIN_DEFAULT_PASSWORD=/run/secrets/pg_admin_password
    env_file: 
      - ./docker/environment/pgadmin.env
    networks:
      - kubes_network
