networks:
  kubes_network:
    driver: bridge

volumes:
  PostgresData:
  NginxLogs:

services:
  app:
    build: ./mykube
    container_name: app_django_kubes
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./docker/environment/django.env
    ports:
      - 8000:8000
    networks:
      - kubes_network

  quart:
    build: ./quart_api
    container_name: app_api_quart
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./docker/environment/quart.env
    ports:
      - 5000:5000
    networks:
      - kubes_network

  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kubes_network

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    networks:
      - kubes_network
