networks:
  kubes_network:
    driver: bridge

volumes:
  PostgresData:
  NginxLogs:

services:
  app:
    build: ./mykube
    container_name: app_django_kubes
    env_file:
      - ./docker/environment/django.env
    ports:
      - 8000:8000
    networks:
      - kubes_network

  quart_api:
    build: ./quart_api
    container_name: app_api_quart
    env_file:
      - ./docker/environment/quart.env
    ports:
      - 5000:5000
    networks:
      - kubes_network

  frontend:
    build: ./frontend
    container_name: app_front_django_kubes
    environment:
      - VITE_PRODUCTION_API_URL=https://example.com/api/v1/
    volumes:
      - ./dist:/app/dist:rw
    ports:
      - 5173:5173
