apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: | 
    user nginx;
    error_log /var/log/nginx/error.log warn;

    http {
        gzip on;
        gzip_min_length 256;

        access_log /var/log/nginx/access.log;
        
        upstream app {
            server app:8000;
        }
        
        server {
            name "gency313.fr"

            location / {
                listen 80 default_server;
                listen [::]:80 default_server ipv6only=on;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                add_header X-Content-Type-Options nosniff;
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Frame-Options SAMEORIGIN;
                add_header Cache-Control "private, max-age=0";

                add_header Allow "GET, POST, HEAD" always;

                if ( $request_method !~ ^(GET|POST|HEAD)$ ) {
                    return 444;
                }

                if ( $http_user_agent = "" ) {
                    return 400;
                }

                proxy_pass http://app;
            }
        }
    }
