apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
        - name: nginx-temp
          emptyDir: {}
        - name: nginx-http-conf
          configMap:
            name: nginx.conf
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
      - name: nginx-app
        image: nginx:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-temp
            mountPath: /mnt/data/
          - name: nginx.conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.
            readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: nginx-port
