kind: Service
apiVersion: v1
metadata:
  name: nginx-srv
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http-ngninx
  - port: 443
    targetPort: 443
    name: https-nginx
