apiVersion: apps/v1
kind: Deployment
metadata:
  name: quart-depl
spec:
  selector:
    matchLabels:
      app: quart-app
  template:
    metadata:
      labels:
        app: quart-app
    spec:
      volumes:
      - name: quart-data
        persistentVolumeClaim:
          claimName: quart-pvc
      - name: quart-temp
        emptyDir: {}
      containers:
      - name: quart-pod
        image: python:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: quart-data
          mountPath: /mnt/pvc/
        - name: quart-temp
          mountPath: /mnt/temp/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
