apiVersion: apps/v1
kind: Deployment
metadata:
  name: quart-depl
  # namespace: ingress-nginx
  labels:
    app: django-kubes
spec:
  selector:
    matchLabels:
      app: quart-app
  template:
    metadata:
      labels:
        app: quart-app
    spec:
      volumes:
      - name: quart-data
        persistentVolumeClaim:
          claimName: quart-pvc
      - name: quart-temp
        emptyDir: {}
      containers:
      - name: quart-pod
        image: django_kubes-quart_api:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: quart-data
          mountPath: /mnt/pvc/
        - name: quart-temp
          mountPath: /mnt/temp/
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
