apiVersion: v1
kind: Secret
metadata:
  name: quart-secret
  labels:
    app: quart-app
type: Opaque
data:
  secret_key: ZUFIMlIwaElrdUEzUkRENnhsRVhsbHRQU0lnRWNIdG8zVVkxVUN5QUdYSWhaVHRMT0RkWmxMWVAxV1RJZ1lrSw==
