apiVersion: v1
kind: Service
metadata:
  name: quart-serv
  # namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: quart-app
  ports:
  - port: 5000
    targetPort: 5000
    name: quart-serv-port
