apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quart-pvc
  # namespace: ingress-nginx
spec:
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
