apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-in-pvc
  namespace: ingress-nginx
spec:
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
