global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: example_site
    scrape_interval: 240s
    metrics_path: /metrics
    static_configs:
      - targets: ["johnpm.fr"]
    tls_config:
      insecure_skip_verify: false
    basic_auth:
      username: "example@gmail.com"
      password: "iCTRbga6objFevofc"
